### ISSUE TITLE
Upgrade tweepy to 3.2.0

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/social-feed-manager#304]
#260 requires tweepy>=3.1.0 in order to use api.statuses_lookup .  However, tweepy 3 breaks some parts of the SFM code.  Known so far:
- tweepy has removed the ```secure``` parameter in the API wrapper (removed, not deprecated - so trying to use it throws an exception)
- There also seems to be different behavior with api.last_response - with tweepy 3.2.0, it is sometimes not present, which throws an error in our user_timeline management command (and possibly other places)
- Possibly others.  Testing should be quite thorough.  Unfortunately the tweepy documentation does not seem to provide release notes documenting what changed in each release, so it's more difficult to bound what is more likely to break, so everything should be tested.

**Comment by kerchner** [comment]
Note that this upgrade also presents some opportunities:  Tweepy has added some new parameters to the API wrapper (http://docs.tweepy.org/en/v3.2.0/api.html#API) such as ```wait_on_rate_limit``` which may allow us to remove some code from SFM and let tweepy do the work.

**Comment by edsu** [comment]
Since tweepy is not pinned in the requirements.txt I installed v3.2.0. As indicated above `tweepy.API` no longer accepts the secure parameter. This caused me to have to go spelunking through the code to figure out what the problem was since I thought I had all my API keys set correctly. I doubt many people installing SFM would have the patience for that. I suggest you pin tweepy to the version that works until the upgrade to v3.2.0 is ready.

**Comment by kerchner** [comment]
@edsu m5_002 has already been released, and i would recommend pinning tweepy to 2.3.0 if you are trying to run m5_002 (or master as of today).  Once https://github.com/gwu-libraries/social-feed-manager/pull/310 is merged, then master will be pinned to 3.2.0 and will have the ```secure``` parameter removed.

**Comment by edsu** [comment]
Time to do another release IMHO since I've counted at least three people with this problem.

**Comment by kerchner** [comment]
Fixed in #310 .  Closing issue.
