### ISSUE TITLE
supervisord not reloading twitterfilter when values in field are changed for an active filter.

### ISSUE THREAD

**Issue by anksharm** [gwu-libraries/social-feed-manager#329]
A change in the values of any fields for any active filter is not picked up by supervisord. 
Current workaround involves, deactivating the filter and then activating it again with the new changes.

**Comment by kerchner** [comment]
Consider upgrading version of supervisord if possible?

**Comment by anksharm** [comment]
Upgrading supervisord did not help. :(

**Comment by kerchner** [comment]
@rajatvij reassigning to you.  As discussed:
- it looks like we _do_ want to restart the process when an Active filter was changed (i.e. where is_active remains True, but some other value changed).  Merely overwriting the conf file doesn't do anything, since the conf file stays exactly the same!  All that changed are values in the database which the process pulls from upon start.
- If we simply change the post_save logic where is_active=True, and add a line to remove the conf file (then reload_config), then rewriting the file, this may work but may also throw an exception upon trying to remove a file that doesn't exist (in the case where it's going from Inactive to Active)
- If we instead try to isolate the case where it's going from Active to Active, that may require more clever use of Django signals - considering use of the update_fields parameter, perhaps using a save signal instead of (or in addition to) post_save signal, etc.

**Comment by kerchner** [comment]
Fixed by #343
